# -*- coding: utf-8 -*-
"""generar_hash.pyipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pFiGzq8_t3IhIwYmSoPboaCN18g10Sf
"""

import streamlit_authenticator as stauth

hashed_passwords = stauth.Hasher(['SportDataCampus']).generate()
print(hashed_passwords)