# -*- coding: utf-8 -*-
"""stauth.Hasher().ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rphky-zOpTdAgGsr-RtOhB4FKe5xxdEV
"""

import streamlit_authenticator as stauth
passwords = ['password123']
hashed_passwords = stauth.Hasher(passwords).generate()
print(hashed_passwords)